/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default'];
    BasicList: typeof import('./components/BasicList.vue')['default'];
    ChooseDepartment: typeof import('./components/ChooseDepartment/index.vue')['default'];
    Empty: typeof import('./components/Empty/index.vue')['default'];
    Indicator: typeof import('./components/Indicator/index.vue')['default'];
    Inedx: typeof import('./components/EmptyData/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SpecialButton: typeof import('./components/SpecialButton/index.vue')['default'];
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent'];
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent'];
    VarBadge: typeof import('@varlet/ui')['_BadgeComponent'];
    VarBreadcrumb: typeof import('@varlet/ui')['_BreadcrumbComponent'];
    VarBreadcrumbs: typeof import('@varlet/ui')['_BreadcrumbsComponent'];
    VarButton: typeof import('@varlet/ui')['_ButtonComponent'];
    VarCell: typeof import('@varlet/ui')['_CellComponent'];
    VarChip: typeof import('@varlet/ui')['_ChipComponent'];
    VarEllipsis: typeof import('@varlet/ui')['_EllipsisComponent'];
    VarIcon: typeof import('@varlet/ui')['_IconComponent'];
    VarList: typeof import('@varlet/ui')['_ListComponent'];
    VarMenu: typeof import('@varlet/ui')['_MenuComponent'];
    VarPopup: typeof import('@varlet/ui')['_PopupComponent'];
    VarPullRefresh: typeof import('@varlet/ui')['_PullRefreshComponent'];
    VarSkeleton: typeof import('@varlet/ui')['_SkeletonComponent'];
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent'];
    VarSticky: typeof import('@varlet/ui')['_StickyComponent'];
  }
}
